# Generated by Django 4.1.6 on 2023-04-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('frequency_morning', models.BooleanField(default=False)),
                ('frequency_afternoon', models.BooleanField(default=False)),
                ('frequency_night', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
