# Generated by Django 4.1.6 on 2023-04-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=500)),
                ('frequency_morning', models.BooleanField(default=False)),
                ('frequency_afternoon', models.BooleanField(default=False)),
                ('frequency_night', models.BooleanField(default=False)),
                ('referencelink', models.CharField(max_length=20)),
                ('detailedexplanation', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
