# Generated by Django 4.1.6 on 2023-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='referencelink',
            field=models.CharField(max_length=500),
        ),
    ]
